name: "FRP Client"
version: "0.1.0"
slug: "frp_client"
description: "FRP client (frpc) for Home Assistant OS"
startup: services
boot: auto
arch:
  - aarch64
  - amd64
  - armv7
options:
  server_addr: "frps.example.com"
  server_port: 7000
  token: "my_secret"
  proxy_name: "ha"
  custom_domains: "ha.example.com"
schema:
  server_addr: str
  server_port: int
  token: str
  proxy_name: str
  custom_domains: str
